package bo.com.offercruz.entidades;
// Generated 20-nov-2014 4:32:22 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private Imagen imagen;
     private String nombre;
     private String apellido;
     private String telefono;
     private int estado;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String bio;
     private String genero;
     private Date fechaNacimiento;
     private Set subscripcions = new HashSet(0);
     private Set solicituds = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Usuario usuario, Imagen imagen, String nombre, String apellido, String telefono, int estado, Date fechaCreacion, Date fechaModificacion) {
        this.usuario = usuario;
        this.imagen = imagen;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.estado = estado;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
    }
    public Cliente(Usuario usuario, Imagen imagen, String nombre, String apellido, String telefono, int estado, Date fechaCreacion, Date fechaModificacion, String bio, String genero, Date fechaNacimiento, Set subscripcions, Set solicituds) {
       this.usuario = usuario;
       this.imagen = imagen;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.estado = estado;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.bio = bio;
       this.genero = genero;
       this.fechaNacimiento = fechaNacimiento;
       this.subscripcions = subscripcions;
       this.solicituds = solicituds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getBio() {
        return this.bio;
    }
    
    public void setBio(String bio) {
        this.bio = bio;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set getSubscripcions() {
        return this.subscripcions;
    }
    
    public void setSubscripcions(Set subscripcions) {
        this.subscripcions = subscripcions;
    }
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }




}


