package bo.com.offercruz.entidades;
// Generated 20-nov-2014 4:32:22 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contenido generated by hbm2java
 */
public class Contenido implements java.io.Serializable {

    private Integer id;
    private int tipoContenido;
    private String titulo;
    private String descripcion;
    private Empresa empresa;
    private int estado;
    private Date fechaPublicacion;
    private Date fechaExpiracion;
    private Date fechaCreacion;
    private Date fechaModificacion;
    private Set ofertas = new HashSet(0);
    private Set imagens = new HashSet(0);
    private Set solicituds = new HashSet(0);

    public Contenido() {
    }

    public Contenido(int tipoContenido, Empresa empresa, String titulo, String descripcion, int estado, Date fechaPublicacion, Date fechaExpiracion, Date fechaCreacion, Date fechaModificacion) {
        this.tipoContenido = tipoContenido;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.empresa = empresa;
        this.estado = estado;
        this.fechaPublicacion = fechaPublicacion;
        this.fechaExpiracion = fechaExpiracion;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
    }

    public Contenido(int tipoContenido, Empresa empresa, String titulo, String descripcion, int estado, Date fechaPublicacion, Date fechaExpiracion, Date fechaCreacion, Date fechaModificacion, Set ofertas, Set imagens) {
        this.tipoContenido = tipoContenido;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.estado = estado;
        this.empresa = empresa;
        this.fechaPublicacion = fechaPublicacion;
        this.fechaExpiracion = fechaExpiracion;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.imagens = imagens;
        this.ofertas = ofertas;
    }

    public Integer getId() {
        return this.id;
    }

    public Empresa getEmpresa() {
        return empresa;
    }

    public Set getOfertas() {
        return ofertas;
    }

    public void setOfertas(Set ofertas) {
        this.ofertas = ofertas;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getTipoContenido() {
        return this.tipoContenido;
    }

    public void setTipoContenido(int tipoContenido) {
        this.tipoContenido = tipoContenido;
    }

    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public int getEstado() {
        return this.estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }

    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }

    public Date getFechaExpiracion() {
        return this.fechaExpiracion;
    }

    public void setFechaExpiracion(Date fechaExpiracion) {
        this.fechaExpiracion = fechaExpiracion;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public Set getImagens() {
        return this.imagens;
    }

    public void setImagens(Set imagens) {
        this.imagens = imagens;
    }

    public Set getSolicituds() {
        return this.solicituds;
    }

    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }

}
