package bo.com.offercruz.entidades;
// Generated 20-nov-2014 4:32:22 by Hibernate Tools 3.6.0



/**
 * Detallesolicitud generated by hbm2java
 */
public class Detallesolicitud  implements java.io.Serializable {


     private int id;
     private Solicitud solicitud;
     private Oferta oferta;
     private Detallecontenido detallecontenido;
     private Integer cantidad;
     private Double precioUnitario;
     private Double montoDetalle;
     private int tipoOfertaDetalleSolicitud;

    public Detallesolicitud() {
    }

	
    public Detallesolicitud(int id, Solicitud solicitud, Oferta oferta, int tipoOfertaDetalleSolicitud) {
        this.id = id;
        this.solicitud = solicitud;
        this.oferta = oferta;
        this.tipoOfertaDetalleSolicitud = tipoOfertaDetalleSolicitud;
    }
    public Detallesolicitud(int id, Solicitud solicitud, Oferta oferta, Detallecontenido detallecontenido, Integer cantidad, Double precioUnitario, Double montoDetalle, int tipoOfertaDetalleSolicitud) {
       this.id = id;
       this.solicitud = solicitud;
       this.oferta = oferta;
       this.detallecontenido = detallecontenido;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.montoDetalle = montoDetalle;
       this.tipoOfertaDetalleSolicitud = tipoOfertaDetalleSolicitud;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }
    public Detallecontenido getDetallecontenido() {
        return this.detallecontenido;
    }
    
    public void setDetallecontenido(Detallecontenido detallecontenido) {
        this.detallecontenido = detallecontenido;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Double getMontoDetalle() {
        return this.montoDetalle;
    }
    
    public void setMontoDetalle(Double montoDetalle) {
        this.montoDetalle = montoDetalle;
    }
    public int getTipoOfertaDetalleSolicitud() {
        return this.tipoOfertaDetalleSolicitud;
    }
    
    public void setTipoOfertaDetalleSolicitud(int tipoOfertaDetalleSolicitud) {
        this.tipoOfertaDetalleSolicitud = tipoOfertaDetalleSolicitud;
    }




}


