package bo.com.offercruz.entidades;
// Generated 20-nov-2014 4:32:22 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Imagen generated by hbm2java
 */
public class Imagen  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Integer ancho;
     private Integer alto;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private int estado;
     private String imagenFisica;
     private Set ofertas = new HashSet(0);
     private Set empresas = new HashSet(0);
     private Set empresas_1 = new HashSet(0);
     private Set clientes = new HashSet(0);
     private Set contenidos = new HashSet(0);
     private Set clientes_1 = new HashSet(0);
     private Set ofertas_1 = new HashSet(0);

    public Imagen() {
    }

	
    public Imagen(String nombre, Date fechaCreacion, Date fechaModificacion, int estado, String imagenFisica) {
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.estado = estado;
        this.imagenFisica = imagenFisica;
    }
    public Imagen(String nombre, Integer ancho, Integer alto, Date fechaCreacion, Date fechaModificacion, int estado, String imagenFisica, Set ofertas, Set empresas, Set empresas_1, Set clientes, Set contenidos, Set clientes_1, Set ofertas_1) {
       this.nombre = nombre;
       this.ancho = ancho;
       this.alto = alto;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estado = estado;
       this.imagenFisica = imagenFisica;
       this.ofertas = ofertas;
       this.empresas = empresas;
       this.empresas_1 = empresas_1;
       this.clientes = clientes;
       this.contenidos = contenidos;
       this.clientes_1 = clientes_1;
       this.ofertas_1 = ofertas_1;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getAncho() {
        return this.ancho;
    }
    
    public void setAncho(Integer ancho) {
        this.ancho = ancho;
    }
    public Integer getAlto() {
        return this.alto;
    }
    
    public void setAlto(Integer alto) {
        this.alto = alto;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public String getImagenFisica() {
        return this.imagenFisica;
    }
    
    public void setImagenFisica(String imagenFisica) {
        this.imagenFisica = imagenFisica;
    }
    public Set getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set ofertas) {
        this.ofertas = ofertas;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }
    public Set getEmpresas_1() {
        return this.empresas_1;
    }
    
    public void setEmpresas_1(Set empresas_1) {
        this.empresas_1 = empresas_1;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getContenidos() {
        return this.contenidos;
    }
    
    public void setContenidos(Set contenidos) {
        this.contenidos = contenidos;
    }
    public Set getClientes_1() {
        return this.clientes_1;
    }
    
    public void setClientes_1(Set clientes_1) {
        this.clientes_1 = clientes_1;
    }
    public Set getOfertas_1() {
        return this.ofertas_1;
    }
    
    public void setOfertas_1(Set ofertas_1) {
        this.ofertas_1 = ofertas_1;
    }




}


