package bo.com.offercruz.entidades;
// Generated 20-nov-2014 4:32:22 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oferta generated by hbm2java
 */
public class Oferta  implements java.io.Serializable {


     private Integer id;
     private Imagen imagen;
     private Categoria categoria;
     private Empresa empresa;
     private String descripcion;
     private String nombre;
     private int estado;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private int tipoOferta;
     private Double precioUnitario;
     private Set detallecontenidos = new HashSet(0);
     private Set detallecontenidos_1 = new HashSet(0);
     private Set detallesolicituds = new HashSet(0);

    public Oferta() {
    }

	
    public Oferta(Categoria categoria, Empresa empresa, String descripcion, String nombre, int estado, Date fechaCreacion, Date fechaModificacion, int tipoOferta) {
        this.categoria = categoria;
        this.empresa = empresa;
        this.descripcion = descripcion;
        this.nombre = nombre;
        this.estado = estado;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.tipoOferta = tipoOferta;
    }
    public Oferta(Imagen imagen, Categoria categoria, Empresa empresa, String descripcion, String nombre, int estado, Date fechaCreacion, Date fechaModificacion, int tipoOferta, Double precioUnitario, Set detallecontenidos, Set detallecontenidos_1, Set detallesolicituds) {
       this.imagen = imagen;
       this.categoria = categoria;
       this.empresa = empresa;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.estado = estado;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.tipoOferta = tipoOferta;
       this.precioUnitario = precioUnitario;
       this.detallecontenidos = detallecontenidos;
       this.detallecontenidos_1 = detallecontenidos_1;
       this.detallesolicituds = detallesolicituds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public int getTipoOferta() {
        return this.tipoOferta;
    }
    
    public void setTipoOferta(int tipoOferta) {
        this.tipoOferta = tipoOferta;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Set getDetallecontenidos() {
        return this.detallecontenidos;
    }
    
    public void setDetallecontenidos(Set detallecontenidos) {
        this.detallecontenidos = detallecontenidos;
    }
    public Set getDetallecontenidos_1() {
        return this.detallecontenidos_1;
    }
    
    public void setDetallecontenidos_1(Set detallecontenidos_1) {
        this.detallecontenidos_1 = detallecontenidos_1;
    }
    public Set getDetallesolicituds() {
        return this.detallesolicituds;
    }
    
    public void setDetallesolicituds(Set detallesolicituds) {
        this.detallesolicituds = detallesolicituds;
    }




}


