package bo.com.offercruz.entidades;
// Generated 20-nov-2014 4:32:22 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private int estado;
     private Date fechaModificacion;
     private Date fechaCreacion;
     private Set permisos = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set usuarios_1 = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(String nombre, String descripcion, int estado, Date fechaModificacion, Date fechaCreacion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.estado = estado;
        this.fechaModificacion = fechaModificacion;
        this.fechaCreacion = fechaCreacion;
    }
    public Perfil(String nombre, String descripcion, int estado, Date fechaModificacion, Date fechaCreacion, Set permisos, Set usuarios, Set usuarios_1) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaModificacion = fechaModificacion;
       this.fechaCreacion = fechaCreacion;
       this.permisos = permisos;
       this.usuarios = usuarios;
       this.usuarios_1 = usuarios_1;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getUsuarios_1() {
        return this.usuarios_1;
    }
    
    public void setUsuarios_1(Set usuarios_1) {
        this.usuarios_1 = usuarios_1;
    }




}


