package bo.com.offercruz.entidades;
// Generated 20-nov-2014 4:32:22 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private Integer id;
     private String permisoTexto;
     private Integer permisoPadreId;
     private int estado;
     private String permisoPagina;
     private String comando;
     private Set perfils = new HashSet(0);

    public Permiso() {
    }

	
    public Permiso(int estado) {
        this.estado = estado;
    }
    public Permiso(String permisoTexto, Integer permisoPadreId, int estado, String permisoPagina, String comando, Set perfils) {
       this.permisoTexto = permisoTexto;
       this.permisoPadreId = permisoPadreId;
       this.estado = estado;
       this.permisoPagina = permisoPagina;
       this.comando = comando;
       this.perfils = perfils;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPermisoTexto() {
        return this.permisoTexto;
    }
    
    public void setPermisoTexto(String permisoTexto) {
        this.permisoTexto = permisoTexto;
    }
    public Integer getPermisoPadreId() {
        return this.permisoPadreId;
    }
    
    public void setPermisoPadreId(Integer permisoPadreId) {
        this.permisoPadreId = permisoPadreId;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public String getPermisoPagina() {
        return this.permisoPagina;
    }
    
    public void setPermisoPagina(String permisoPagina) {
        this.permisoPagina = permisoPagina;
    }
    public String getComando() {
        return this.comando;
    }
    
    public void setComando(String comando) {
        this.comando = comando;
    }
    public Set getPerfils() {
        return this.perfils;
    }
    
    public void setPerfils(Set perfils) {
        this.perfils = perfils;
    }




}


