package bo.com.offercruz.entidades;
// Generated 20-nov-2014 4:32:22 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud implements java.io.Serializable {

    private Integer id;
    private Cliente cliente;
    private Empresa empresa;
    private Contenido contenido;
    private int estado;
    private Date fechaCreacion;
    private Date fechaModificacion;
    private String telefonoClienteTransaccion;
    private Double totalEstimadoSolicitud;

    public Solicitud() {
    }

    public Solicitud(Cliente cliente, Empresa empresa, int estado, Date fechaCreacion, Date fechaModificacion, String telefonoClienteTransaccion) {
        this.cliente = cliente;
        this.empresa = empresa;
        this.estado = estado;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.telefonoClienteTransaccion = telefonoClienteTransaccion;
    }

    public Solicitud(Cliente cliente, Empresa empresa, Contenido contenido, int estado, Date fechaCreacion, Date fechaModificacion, String telefonoClienteTransaccion, Double totalEstimadoSolicitud) {
        this.cliente = cliente;
        this.empresa = empresa;
        this.contenido = contenido;
        this.estado = estado;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.telefonoClienteTransaccion = telefonoClienteTransaccion;
        this.totalEstimadoSolicitud = totalEstimadoSolicitud;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public Contenido getContenido() {
        return this.contenido;
    }

    public void setContenido(Contenido contenido) {
        this.contenido = contenido;
    }

    public int getEstado() {
        return this.estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }

    public String getTelefonoClienteTransaccion() {
        return this.telefonoClienteTransaccion;
    }

    public void setTelefonoClienteTransaccion(String telefonoClienteTransaccion) {
        this.telefonoClienteTransaccion = telefonoClienteTransaccion;
    }

    public Double getTotalEstimadoSolicitud() {
        return this.totalEstimadoSolicitud;
    }

    public void setTotalEstimadoSolicitud(Double totalEstimadoSolicitud) {
        this.totalEstimadoSolicitud = totalEstimadoSolicitud;
    }

}
