package bo.com.offercruz.entidades;
// Generated 20-nov-2014 4:32:22 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Subscripcion generated by hbm2java
 */
public class Subscripcion  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private Empresa empresa;
     private Date fechaSubscripcion;
     private int estado;

    public Subscripcion() {
    }

    public Subscripcion(Cliente cliente, Empresa empresa, Date fechaSubscripcion, int estado) {
       this.cliente = cliente;
       this.empresa = empresa;
       this.fechaSubscripcion = fechaSubscripcion;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Date getFechaSubscripcion() {
        return this.fechaSubscripcion;
    }
    
    public void setFechaSubscripcion(Date fechaSubscripcion) {
        this.fechaSubscripcion = fechaSubscripcion;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }




}


